org: ngocnhelife # Enter your tenant name here
app: workshop # Enter your application name here
service: fullstack-restapi # update

plugins:
   - serverless-appsync-plugin

params:
  default:
    name: nguyenngoc
  dev:
    name: buihong
  prod:
    name: aki

custom:
  nenv: ${param:env, "ngocnh"}
  name: ${param:name, param:name}

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-west-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource: "arn:aws:dynamodb:*:*:table/${output:workshop:${param:env, self:provider.stage}::database.database_submissions_name}"

functions:
  getUser:
    handler: functions/getUser.lambda_handler
    timeout: 10

outputs:
  var1: ${self:custom.nenv}
  var2: ${self:custom.name}
