org: ngocnhelife # Enter your tenant name here
app: workshop # Enter your application name here
service: fullstack-restapi # update

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-2
  params:
    default:
      name: nguyenngoc
    dev:
      name: buihong
    prod:
      name: aki
  custom:
    nenv: ${param:env, "ngocnh"}
    name: ${param:name}
  environment:
    database_submissions_name: ${output:${self:app}:${param:env, self:provider.stage}::database.database_submissions_name}
    database_submissions_region: ${output:workshop:${param:env, self:provider.stage}::database.database_submissions_region}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource: "arn:aws:dynamodb:*:*:table/${output:workshop:${param:env, self:provider.stage}::database.database_submissions_name}"

functions:
  formSubmit:
    handler: index.submit
    timeout: 10
    events:
      - http:
          path: submit
          method: post
          cors: true

output:
  var1: ${self:custom.nenv}
  var2: ${self:custom.name}
